### ISSUE TITLE
Additional provider required for Unit Testing an Ionic2 project

### ISSUE THREAD

**Issue by CoreyCole** [lathonez/lathonez.github.io#4]
When following the [Unit Testing an Ionic2 project](http://lathonez.github.io/2016/ionic-2-unit-testing/) tutorial, I ran into an error running the simple test.
```
Error: No provider for GestureController!
```
I fixed this by adding the following to my `test.ts` file:
```
import { App, MenuController, NavController, Platform, Config, Keyboard, Form, IonicModule, GestureController }  from 'ionic-angular';
```
...
```
providers: [
  App, Platform, Form, Keyboard, MenuController, NavController, GestureController,
  {provide: Config, useClass: ConfigMock}
]
```

I'd love to know more about why this happened. My project was generated using the ionic-cli after the release of rc3.

## Environment
```
"ionic-angular": "2.0.0-rc.3"
"angular-cli": "^1.0.0-beta.22-1"
"karma": "1.3.0"
```

**Comment by lathonez** [comment]
Hi Cory,

Lots of people have ran into this issue. Something you are using requires
the GestureController:

https://github.com/lathonez/clicker/issues/154
https://github.com/lathonez/clicker/issues/160
https://github.com/lathonez/clicker/issues/180

Thanks

**Comment by CoreyCole** [comment]
Thanks lathonez, I guess I was looking in the wrong repo for issues :)
