### ISSUE TITLE
All tests not working anymore

### ISSUE THREAD

**Issue by alain-sarti** [lathonez/lathonez.github.io#5]
Hi there,

I followed your tutorial and everything worked fine. The e2e tests still work, but as of today (or at least I saw it today), the unit test part results in the following message:

> It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and has a lot of improvements including a simpler
workflow, a faster build, and smaller bundles.
>
> To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14

The app I'm trying that on was created yesterday. Do you have any ideas what the problem might be?

**Comment by lathonez** [comment]
Hi,

In future could you technical issues with the framework against the [clicker repo](https://github.com/lathonez/clicker/issues)?

This is for issues with the blog (typos / inaccuracies).

Here are things to try:

1 - clone the clicker repo, install deps and make sure all tests pass
2 - if (1) was OK, you probably have some out of date config in your project. Compare your project with clicker to see what the differences are.

If you need further assistance please reopen in the correct repo.

Thanks
